package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecord<M extends BaseRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setStuIds(java.lang.String stuIds) {
		set("stuIds", stuIds);
		return (M)this;
	}
	
	public java.lang.String getStuIds() {
		return getStr("stuIds");
	}

	public M setLoantimes(java.util.Date loantimes) {
		set("loantimes", loantimes);
		return (M)this;
	}
	
	public java.util.Date getLoantimes() {
		return get("loantimes");
	}

	public M setBacktimes(java.util.Date backtimes) {
		set("backtimes", backtimes);
		return (M)this;
	}
	
	public java.util.Date getBacktimes() {
		return get("backtimes");
	}

	public M setOrders(java.lang.Long orders) {
		set("orders", orders);
		return (M)this;
	}
	
	public java.lang.Long getOrders() {
		return getLong("orders");
	}

	public M setGoodsname(java.lang.String goodsname) {
		set("goodsname", goodsname);
		return (M)this;
	}
	
	public java.lang.String getGoodsname() {
		return getStr("goodsname");
	}

	public M setStunames(java.lang.String stunames) {
		set("stunames", stunames);
		return (M)this;
	}
	
	public java.lang.String getStunames() {
		return getStr("stunames");
	}

}
