package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseGoods;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods().dao();
	
	public Page<Goods> paginate(int pageNumber, int pageSize) {
		return dao.paginate(pageNumber, pageSize, "select *", " from goods order by orders asc");
	}
	
	public List<Goods> findByStateHad() {
		return Goods.dao.find("select * from goods where state=" + 0);
	}
	
//	public List<Goods> findByStateLend() {
//		return Goods.dao.find("select * from goods where state=" + 1);
//	}
	
	public Goods findByOrder(String orders) {
		return Goods.dao.findFirst("select * from goods where orders=?", orders);
	}
	
	public List<Goods> findAll()
	{
		return Goods.dao.find("select * from goods");
	}
	
	public List<Goods> getList() {
		return Goods.dao.find("select * from goods order by orders asc");
	}
	
	
}
