package com.demo.common.model;

import java.util.List;
import com.demo.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	/**
	 * 查询登陆者姓名
	 */
	public User findByUserName(String userName)
	{
		return User.dao.findFirst("SELECT * FROM user WHERE name=?",userName);
	}
	
	public List<User> findAll()
	{
		return User.dao.find("SELECT * FROM uer");
	}
	
	/**
	 * 查询登录者账号
	 */
	public User checkStuId(String username)
	{
		return User.dao.findFirst("select * from user where studId=?",username);
	}
	
	/**
	 * 查询登录者密码
	 */
	public User checkPassward(String username, String password) {
		return User.dao.findFirst("SELECT * FROM user WHERE studId=? AND passward=?", username, password); 
	}
	
	public User findByStudId(String name) {
		return User.dao.findFirst("select * from user where studId=?", name);
	}
	
	/**
	 * 查看审核
	 */
	public List<User> findByTypeAuditing() {
		return User.dao.find("select * from user where type=?", 0);
	}
}
